music/urls.py
from django.conf.urls import url

# importing views for current url mappings
from . import views




urlpatterns = [

	# /music/
    url(r'^$', views.index, name='index'),
    # /music/62
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

website/urls.py
# include - imports url mappings from other urls.py files from included apps
from django.conf.urls import include, url
from django.contrib import admin




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length = 250)
	album_title = models.CharField(max_length = 250)
	genre = models.CharField(max_length = 100)
	album_logo = models.CharField(max_length = 1000)
	
	def __str__(self):
		return self.album_title +  ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	filetype = models.CharField(max_length = 10)
	song_title = models.CharField(max_length = 250)

	def __str__(self):
		return self.song_title

music/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Album

def index(request):
	# grab all the albums from the database and assign them to an object
	all_albums = Album.objects.all()
	
	# provide 'context' to the view that allows it to access to the object holding the data
	context = {"all_albums" : all_albums,}	

	# render the page, while passing it the data
	return render(request, 'music/index.html', context)

def detail(request, album_id):
	try:
		album = Album.objects.get(pk=album_id)
	except Album.DoesNotExist:
		raise Http404(" Album does not exist")
	return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src="{{ album.album_logo }}" alt="">
<h1> {{album.album_title}}</h1>
<h3>{{album.artist}}</h3>
<ul>
	{% for song in album.song_set.all%}
	<li>{{ song.song_title}} - {{song.file_type}}</li>
	{% endfor %}
</ul>

music/templates/music/index.html
{% if all_albums %}
<ul>
	<h3>List of Avaliable Albums: <br></h3>
	{% for album in all_albums %}
	<!-- dynamic url -->
	<li><a href="{% url 'detail' album.id %}">{{ album.album_title }}</a></li>
	{% endfor %}
</ul>
{% else %}
	<h3>No albums avaliable</h3>
{% endif %}